version: "3.7"

networks:
  parseable-internal:

services:
  panorama:
    image: ghcr.io/aldrinjenson/panorama:main
    networks:
      - parseable-internal
    depends_on:
      - parseable
    environment:
      - PANORAMA_ADDRESS="http://panorama:5000"
      - PANORAMA_ADMIN_USERNAME=pano_admin
      - PANORAMA_ADMIN_PASSWORD=pano_admin
      - PARSEABLE_USERNAME=parseableadmin # todo: make as env var and use in other jobs
      - PARSEABLE_PASSWORD=parseableadmin
      - PARSEABLE_BASE_URL="http://localhost:8000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 32

  minio:
    image: minio/minio:RELEASE.2023-02-10T18-48-39Z
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /tmp/minio/parseable && \
        minio server /tmp/minio
    environment:
      - MINIO_ROOT_USER=parseable
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_UPDATE=off
    ports:
      - 9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 15s
      timeout: 20s
      retries: 5
    networks:
      - parseable-internal

  parseable:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["parseable", "s3-store"]
    ports:
      - 8000
    environment:
      - P_S3_URL=http://minio:9000
      - P_S3_ACCESS_KEY=parseable
      - P_S3_SECRET_KEY=supersecret
      - P_S3_REGION=us-east-1
      - P_S3_BUCKET=parseable
      - P_STAGING_DIR=/tmp/data
      - P_USERNAME=parseableadmin
      - P_PASSWORD=parseableadmin
      - P_CHECK_UPDATE=false
    networks:
      - parseable-internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/liveness"]
      interval: 15s
      timeout: 20s
      retries: 5
    depends_on:
      - minio
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
  quest:
    image: ghcr.io/aldrinjenson/quest:main
    command: [
        "load",
        "http://parseable:8000",
        "parseableadmin",
        "parseableadmin",
        "20",
        "http://panorama:5000", # todo: make these into env var
        pano_admin,
        pano_admin,
      ]
    networks:
      - parseable-internal
    depends_on:
      - parseable
      - panorama
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
