name: Build Rust for Multiple Architectures

on:
  push:
    branches:
      - arm

jobs:
  build:
    name: Build for Multiple Architectures
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [x86_64-apple-darwin, x86_64-pc-windows-msvc, x86_64-unknown-linux-musl, aarch64-unknown-linux-musl, aarch64-apple-darwin]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build for ${{ matrix.target }}
        run: |
          cargo build --target ${{ matrix.target }} --release

    - name: Publish Archive
      uses: softprops/action-gh-release@v0.1.15
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        draft: false
        files: ${{ steps.package.outputs.archive }}
        prerelease: ${{ steps.check-tag.outputs.rc == 'true' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
