name: Integration

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "helm/**"
      - "assets/**"
      - "**.md"

jobs:
  docker-compose-test:
    name: Quest Smoke and Load Tests
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start compose
        run: docker-compose -f docker-compose-test.yaml up --build --exit-code-from quest
      - name: Stop compose
        if: always()
        run: docker-compose -f docker-compose-test.yaml down
