name: Integration

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "helm/**"
      - "assets/**"
      - "**.md"
  push: # todo: remove this before pr merge
    branches:
      - main

jobs:
  docker-compose-test:
    name: Quest Smoke and Load Tests
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start compose
        run: docker-compose -f docker-compose-test.yaml up --build --exit-code-from quest
      - name: Stop compose
        if: always()
        run: docker-compose -f docker-compose-test.yaml down
