name: Release builds for Mac(64bit, Arm), Windows and Linux(64 bit, Arm)

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "helm/**"
      - "assets/**"
      - "**.md"

jobs:
  build-linux:
    name: Build for ${{matrix.target}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-gnu # linux(arm)
          - x86_64-unknown-linux-gnu # linux(64 bit)
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{matrix.target}}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{matrix.target}}

      - uses: actions/upload-artifact@v3
        with:
          name: Parseable_${{ matrix.target }}
          path: target/${{ matrix.target }}/release/parseable

  build-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release --target x86_64-pc-windows-msvc

      - name: Create artifact for Windows
        uses: actions/upload-artifact@v2
        with:
          name: Parseable_x86_64-pc-windows-msvc
          path: target/x86_64-pc-windows-msvc/release/PARSEABLE.exe

  build-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          default: true
          override: true

      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }}
          strip target/${{ matrix.target }}/release/Parseable
          mv target/${{ matrix.target }}/release/Parseable target/${{ matrix.target }}/release/Parseable_darwin

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: Parseable_${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/Parseable_darwin
