name: Windows build

on: [push]

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release --target x86_64-pc-windows-msvc

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: PARSEABLE
          path: target/x86_64-pc-windows-msvc/release/PARSEABLE.exe
